//! Building a shim plugin as a list of filesystem operations.
//!
//! The generator writes data only. Every generated command invokes the
//! agentsync binary, so a fix to a translation strategy ships with the binary
//! instead of requiring every shim on disk to be rewritten.

use std::collections::BTreeMap;
use std::path::PathBuf;

use anyhow::Result;
use serde_json::{Map, Value, json};

use crate::core::model::{HookHandler, event_key};
use crate::core::plan::FsOp;
use crate::shim::ShimSpec;

/// Everything needed to generate one shim plugin.
pub struct ShimInput {
    /// Directory agentsync owns and registers as a local marketplace.
    pub marketplace_dir: PathBuf,
    /// The original plugin being stood in for.
    pub plugin: String,
    /// The marketplace the original came from.
    pub marketplace: String,
    /// Handlers to emulate, in their original order.
    pub handlers: Vec<HookHandler>,
    /// Top-level stdout keys the target accepts.
    pub allowed_output: Vec<String>,
    /// Keys whose human-readable text moves into `systemMessage`.
    pub fold_into_system_message: Vec<String>,
    /// Absolute path of the agentsync binary the generated commands invoke.
    pub agentsync_bin: PathBuf,
    /// Directories in the ORIGINAL plugin to carry over by symlink, for example
    /// its `skills` and `commands`. The shim replaces the original outright, so
    /// without these that content would disappear. Linking rather than copying
    /// means the shim cannot drift from the original.
    pub vendor: Vec<PathBuf>,
}

pub struct Generated {
    pub ops: Vec<FsOp>,
    /// Name of the generated plugin, for `plugin add`.
    pub shim_plugin: String,
    /// Name of the marketplace it lives in, for `marketplace add`.
    pub marketplace_name: String,
}

/// The marketplace agentsync owns. Named so it cannot collide with a real one.
pub const MARKETPLACE_NAME: &str = "agentsync-shims";

pub fn shim_plugin_name(plugin: &str) -> String {
    format!("agentsync-shim-{plugin}")
}

/// A sidecar file name that is unique per handler and stable across runs.
fn sidecar_name(handler: &HookHandler) -> String {
    format!(
        "{}-{}-{}.json",
        event_key(&handler.event),
        handler.id.group,
        handler.id.index
    )
}

pub fn plan_shim(input: &ShimInput) -> Result<Generated> {
    let shim_plugin = shim_plugin_name(&input.plugin);
    let plugin_dir = input.marketplace_dir.join(&shim_plugin);
    let specs_dir = plugin_dir.join("specs");
    let mut ops = Vec::new();

    // One sidecar per handler. Identity is positional, so two handlers with
    // byte-identical commands still get their own file.
    for handler in &input.handlers {
        let spec = ShimSpec {
            source_id: handler.id.to_string(),
            command: handler.command.clone(),
            plugin_root: handler.plugin_root.clone(),
            if_pattern: handler.if_pattern.clone(),
            allowed_output: input.allowed_output.clone(),
            fold_into_system_message: input.fold_into_system_message.clone(),
        };
        ops.push(FsOp::WriteFile {
            path: specs_dir.join(sidecar_name(handler)),
            contents: spec.to_json()?,
        });
    }

    // The manifest. Groups are rebuilt from the handlers' own group indices, but
    // only groups a handler actually occupies are emitted. An empty padding
    // group would carry no matcher and no hooks, so leaving it out loses
    // nothing while keeping the manifest free of dead entries. Groups keep the
    // relative order of their original index.
    let mut events: BTreeMap<String, BTreeMap<usize, Value>> = BTreeMap::new();
    for handler in &input.handlers {
        let groups = events.entry(handler.event.clone()).or_default();
        let group = groups
            .entry(handler.id.group)
            .or_insert_with(|| json!({ "hooks": [] }));
        if let Some(matcher) = &handler.matcher {
            group["matcher"] = Value::String(matcher.clone());
        }
        let command = format!(
            "{} hook-shim --spec {}",
            shell_quote(&input.agentsync_bin.to_string_lossy()),
            shell_quote(&specs_dir.join(sidecar_name(handler)).to_string_lossy()),
        );
        let mut entry = json!({ "type": "command", "command": command });
        if let Some(timeout) = handler.timeout {
            entry["timeout"] = json!(timeout);
        }
        group["hooks"]
            .as_array_mut()
            .expect("groups are built with a hooks array")
            .push(entry);
    }
    let events: Map<String, Value> = events
        .into_iter()
        .map(|(event, groups)| (event, Value::Array(groups.into_values().collect())))
        .collect();

    let manifest = json!({
        "description": format!(
            "Generated by agentsync so {} can run hooks from {}@{}.",
            "this host", input.plugin, input.marketplace
        ),
        "hooks": Value::Object(events),
    });
    ops.push(FsOp::WriteFile {
        path: plugin_dir.join("hooks/hooks.json"),
        contents: format!("{}\n", serde_json::to_string_pretty(&manifest)?),
    });

    // Carry the original's non-hook content across by symlink. The shim
    // supersedes the original, so anything not carried over is lost.
    for source in &input.vendor {
        if let Some(name) = source.file_name() {
            ops.push(FsOp::Link {
                target: source.clone(),
                link: plugin_dir.join(name),
            });
        }
    }

    let marketplace = json!({
        "name": MARKETPLACE_NAME,
        "plugins": [ { "name": shim_plugin } ],
    });
    ops.push(FsOp::WriteFile {
        path: input
            .marketplace_dir
            .join(".claude-plugin/marketplace.json"),
        contents: format!("{}\n", serde_json::to_string_pretty(&marketplace)?),
    });

    Ok(Generated {
        ops,
        shim_plugin,
        marketplace_name: MARKETPLACE_NAME.to_string(),
    })
}

/// Single-quote a path for `sh -c`. Generated commands run through a shell, and
/// a path with a space would otherwise split into two arguments.
fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::model::{HookHandler, HookId};

    fn handler(index: usize, if_pattern: Option<&str>) -> HookHandler {
        let mut h = HookHandler::new(
            HookId {
                source: "security-guidance@claude-plugins-official:hooks/hooks.json".into(),
                event: "PostToolUse".into(),
                group: 1,
                index,
            },
            "PostToolUse",
            "bash \"${CLAUDE_PLUGIN_ROOT}/hooks/review.sh\"",
        );
        h.matcher = Some("Bash".into());
        h.if_pattern = if_pattern.map(str::to_string);
        h.plugin_root = Some("/cache/claude-plugins-official/security-guidance/2.0.6".into());
        h
    }

    fn input(handlers: Vec<HookHandler>) -> ShimInput {
        ShimInput {
            marketplace_dir: "/home/u/.agentsync/shims/codex".into(),
            plugin: "security-guidance".into(),
            marketplace: "claude-plugins-official".into(),
            handlers,
            allowed_output: vec!["systemMessage".into()],
            fold_into_system_message: vec!["rewakeMessage".into()],
            agentsync_bin: "/usr/local/bin/agentsync".into(),
            vendor: vec![],
        }
    }

    fn written(ops: &[crate::core::plan::FsOp], ends_with: &str) -> String {
        ops.iter()
            .find_map(|op| match op {
                crate::core::plan::FsOp::WriteFile { path, contents }
                    if path.to_string_lossy().ends_with(ends_with) =>
                {
                    Some(contents.clone())
                }
                _ => None,
            })
            .unwrap_or_else(|| panic!("no write op ending in {ends_with}"))
    }

    #[test]
    fn each_handler_gets_its_own_sidecar_carrying_its_own_filter() {
        // Five handlers with byte-identical commands must not collapse. This is
        // the bug the whole domain exists to report.
        let g = plan_shim(&input(vec![
            handler(0, Some("Bash(git commit:*)")),
            handler(1, Some("Bash(git push:*)")),
        ]))
        .unwrap();

        let a: crate::shim::ShimSpec =
            serde_json::from_str(&written(&g.ops, "post_tool_use-1-0.json")).unwrap();
        let b: crate::shim::ShimSpec =
            serde_json::from_str(&written(&g.ops, "post_tool_use-1-1.json")).unwrap();
        assert_eq!(a.if_pattern.as_deref(), Some("Bash(git commit:*)"));
        assert_eq!(b.if_pattern.as_deref(), Some("Bash(git push:*)"));
        assert_eq!(a.command, b.command, "the fixture's commands are identical");
    }

    #[test]
    fn the_sidecar_records_the_originals_plugin_root_not_the_shims() {
        let g = plan_shim(&input(vec![handler(0, None)])).unwrap();
        let spec: crate::shim::ShimSpec =
            serde_json::from_str(&written(&g.ops, "post_tool_use-1-0.json")).unwrap();
        assert_eq!(
            spec.plugin_root.as_deref(),
            Some(std::path::Path::new(
                "/cache/claude-plugins-official/security-guidance/2.0.6"
            ))
        );
    }

    #[test]
    fn the_generated_manifest_keeps_the_event_and_matcher_and_calls_the_shim() {
        let g = plan_shim(&input(vec![handler(0, Some("Bash(git commit:*)"))])).unwrap();
        let manifest: serde_json::Value =
            serde_json::from_str(&written(&g.ops, "hooks/hooks.json")).unwrap();
        let group = &manifest["hooks"]["PostToolUse"][0];
        assert_eq!(group["matcher"], "Bash");
        let command = group["hooks"][0]["command"].as_str().unwrap();
        assert!(command.contains("/usr/local/bin/agentsync"), "{command}");
        assert!(command.contains("hook-shim --spec"), "{command}");
        // The filter is emulated by the runtime, so it must NOT be re-emitted
        // into a manifest the target cannot honour anyway.
        assert!(group["hooks"][0].get("if").is_none());
    }

    #[test]
    fn the_marketplace_manifest_lists_the_generated_plugin() {
        let g = plan_shim(&input(vec![handler(0, None)])).unwrap();
        let mkt: serde_json::Value =
            serde_json::from_str(&written(&g.ops, ".claude-plugin/marketplace.json")).unwrap();
        assert_eq!(mkt["name"], g.marketplace_name);
        let names: Vec<&str> = mkt["plugins"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|p| p["name"].as_str())
            .collect();
        assert!(names.contains(&g.shim_plugin.as_str()), "got {names:?}");
    }

    #[test]
    fn generation_is_byte_stable_so_a_rerun_reports_no_drift() {
        let a = plan_shim(&input(vec![handler(0, Some("Bash(git commit:*)"))])).unwrap();
        let b = plan_shim(&input(vec![handler(0, Some("Bash(git commit:*)"))])).unwrap();
        assert_eq!(format!("{:?}", a.ops), format!("{:?}", b.ops));
    }

    #[test]
    fn the_originals_other_content_is_carried_across_by_symlink() {
        // The shim REPLACES the original, so its skills and commands must come
        // with it. A link rather than a copy means they cannot drift apart.
        let mut i = input(vec![handler(0, None)]);
        i.vendor = vec![
            "/cache/claude-plugins-official/security-guidance/2.0.6/skills".into(),
            "/cache/claude-plugins-official/security-guidance/2.0.6/commands".into(),
        ];
        let g = plan_shim(&i).unwrap();
        let links: Vec<_> = g
            .ops
            .iter()
            .filter_map(|op| match op {
                crate::core::plan::FsOp::Link { target, link } => {
                    Some((target.clone(), link.clone()))
                }
                _ => None,
            })
            .collect();
        assert_eq!(links.len(), 2, "got {links:?}");
        assert!(
            links.iter().any(|(_, link)| link.ends_with("skills")),
            "skills must land under the shim plugin: {links:?}"
        );
    }

    #[test]
    fn a_handler_with_no_plugin_root_still_generates() {
        // A user-level settings hook has no plugin root. It must not be dropped.
        let mut h = handler(0, None);
        h.plugin_root = None;
        let g = plan_shim(&input(vec![h])).unwrap();
        let spec: crate::shim::ShimSpec =
            serde_json::from_str(&written(&g.ops, "post_tool_use-1-0.json")).unwrap();
        assert!(spec.plugin_root.is_none());
    }
}
